
package com.qh.paythird.hx.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;
import javax.xml.namespace.QName;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T10:19:03.708+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class OrderQueryService_WSOrderQuerySoap_Client {

    private static final QName SERVICE_NAME = new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuery");

    /**
     * 
     * @Description 商户号 查询
     * @param xml
     * @return
     */
    public static String getOrderByMerBillNo(String xml){
        URL wsdlURL = WSOrderQuery.WSDL_LOCATION;
        WSOrderQuery ss = new WSOrderQuery(wsdlURL, SERVICE_NAME);
        OrderQueryService port = ss.getWSOrderQuerySoap();
        return port.getOrderByMerBillNo(xml);
    }
    /**
     * 
     * @Description 时间查询
     * @param xml
     * @return
     */
    public static String getOrderByTime(String xml){
        URL wsdlURL = WSOrderQuery.WSDL_LOCATION;
        WSOrderQuery ss = new WSOrderQuery(wsdlURL, SERVICE_NAME);
        OrderQueryService port = ss.getWSOrderQuerySoap();
        return port.getOrderByTime(xml);
    }
    /***
     * 
     * @Description 银行信息查询
     * @param xml
     * @return
     */
    public static String getOrderByBankNo(String xml){
        URL wsdlURL = WSOrderQuery.WSDL_LOCATION;
        WSOrderQuery ss = new WSOrderQuery(wsdlURL, SERVICE_NAME);
        OrderQueryService port = ss.getWSOrderQuerySoap();
        return port.getOrderByBankNo(xml);
    }

}
