package com.qh.paythird.hx.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T10:19:03.766+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery", name = "OrderQueryService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface OrderQueryService {

    @WebMethod(action = "http://payat.ips.com.cn/WebService/OrderQuery/getOrderByTime")
    @WebResult(name = "getOrderByTimeResult", targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery", partName = "getOrderByTimeResult")
    public String getOrderByTime(
            @WebParam(partName = "orderQuery", name = "orderQuery")
                    String orderQuery
    );

    @WebMethod(action = "http://payat.ips.com.cn/WebService/OrderQuery/getOrderByBankNo")
    @WebResult(name = "getOrderByBankNoResult", targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery", partName = "getOrderByBankNoResult")
    public String getOrderByBankNo(
            @WebParam(partName = "orderQuery", name = "orderQuery")
                    String orderQuery
    );

    @WebMethod(action = "http://payat.ips.com.cn/WebService/OrderQuery/getOrderByMerBillNo")
    @WebResult(name = "getOrderByMerBillNoResult", targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery", partName = "getOrderByMerBillNoResult")
    public String getOrderByMerBillNo(
            @WebParam(partName = "orderQuery", name = "orderQuery")
                    String orderQuery
    );
}
