package com.qh.paythird.hx.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-27T10:19:03.781+08:00
 * Generated source version: 3.1.10
 * 
 */
    @WebServiceClient(name = "WSOrderQuery",
                      wsdlLocation = "https://newpay.ips.com.cn/psfp-entry/services/order?wsdl",
                      targetNamespace = "http://payat.ips.com.cn/WebService/OrderQuery")
public class WSOrderQuery extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuery");
    public final static QName WSOrderQuerySoap = new QName("http://payat.ips.com.cn/WebService/OrderQuery", "WSOrderQuerySoap");
    static {
        URL url = null;
        try {
            url = new URL("https://newpay.ips.com.cn/psfp-entry/services/order?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSOrderQuery.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://newpay.ips.com.cn/psfp-entry/services/order?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSOrderQuery(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSOrderQuery(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSOrderQuery() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSOrderQuery(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSOrderQuery(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSOrderQuery(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderQueryService
     */
    @WebEndpoint(name = "WSOrderQuerySoap")
    public OrderQueryService getWSOrderQuerySoap() {
        return super.getPort(WSOrderQuerySoap, OrderQueryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderQueryService
     */
    @WebEndpoint(name = "WSOrderQuerySoap")
    public OrderQueryService getWSOrderQuerySoap(WebServiceFeature... features) {
        return super.getPort(WSOrderQuerySoap, OrderQueryService.class, features);
    }

}
